behaviors:
  Hider:
    trainer_type: ppo
    max_steps: 6000000
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 3.0e-4
      beta: 0.005
      epsilon: 0.2
      num_epoch: 3
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

  Seeker:
    trainer_type: ppo
    max_steps: 6000000
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 1.0e-4
      beta: 0.01
      epsilon: 0.2
      num_epoch: 3
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:    
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.9
        demo_path: Demos/SeekerDemonstrat.demo
    behavioral_cloning:
      strength: 0.9
      demo_path: Demos/SeekerDemonstrat.demo